name: Pipeline WebServer
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Single deploy job since we're just deploying
  deploy:
    
    runs-on: ubuntu-latest

    
    steps:
      - name: Acesso EC2
        run: |
           echo "${{secrets.<nome secret>}}" > webserver && chmod 600 webserver
           ssh -o StrictHostKeyChecking=no -i "webserver.pem" ubuntu@${{secrets.ssh_ubuntu}} "
               cd /var/www/html/;git pull "
